CREATE TABLE sms
(
    id bigint generated by default as identity,
    user_id bigint not null,
    phone_number varchar(20) not null,
    message text not null,
    type varchar(20) not null,
    status varchar(20) not null default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    client_id varchar(100),

    PRIMARY KEY(id, created_at)
)
    PARTITION BY RANGE(created_at);